package:
    name: libmo_unpack
    version: !!str 3.0

source:
    git_url: https://github.com/SciTools/libmo_unpack.git
    git_rev: v3.0

build:
    number: 0  # [not linux]
    number: 1  # [linux]

about:
    home: https://github.com/SciTools/libmo_unpack
    summary: Met Office PP/FieldsFile compression schemes
