package:
  name: cartopy
  version: 0.13.0

source:
  git_url: https://github.com/SciTools/cartopy.git
  git_tag: v0.13.0

  patches:
    - cartopy.win.patch  # [win]

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - six
    # We must bake the numpy version into the build string.
    - numpy *
    - cython
    - proj4
    - geos
    # On OSX We need to effectively pin the geos version to the
    # one used by the specific shapely being targetted (we're letting
    # conda's package solver will deal with that).
    - shapely >=1.5.6
    - owslib
    - pyshp
    - pyepsg
  
  run:
    - python
    - six
    - mock
    - nose
    - pillow
    - owslib
    - numpy
    - proj4
    - shapely >=1.5.6
    - scipy
    - pyshp
    - matplotlib
    - pyepsg

test:
  imports:
    - cartopy
    - cartopy.mpl.geoaxes
    - cartopy.crs

about:
  home: http://scitools.org.uk/cartopy
  license: GNU LGPL
  summary: 'A library providing cartographic tools for python'

