package:
    name: udunits
    version: 2.2.17

source:
    fn: v2.2.17.tar.gz
    url: https://github.com/Unidata/UDUNITS-2/archive/v2.2.17.tar.gz
    sha1: 3dfb7b1f18e21ac5366127778bbfd50ab5b7cf0a

requirements:
  build:
#    - cmake <=2.8
    - expat
  run:
    - expat

build:
    number: 3
    detect_binary_files_with_prefix: true

test:
    commands:
        - udunits2 -h
        # Note: requires UDUNITS2_XML_PATH to be set to the test directory on Windows. UDUNITS is not portable on Windows currently.
        - udunits2 -H meter -W miles

about:
  home: http://www.unidata.ucar.edu/software/udunits/
  summary: The UDUNITS package supports units of physical quantities.
