package:
    name: ecmwf_grib
    version: "1.12.1"

source:
    fn: grib_api-1.12.1.tar.gz
    url: https://software.ecmwf.int/wiki/download/attachments/3473437/grib_api-1.12.1.tar.gz?api=v2
    sha1: b769ac5db70703f0d944d93aafbbeee7513958f1

requirements:
    build:
        - python
        - numpy
        - jasper

    run:
        - python
        - numpy
        - jasper

test:
    imports:
        - gribapi

about:
    home: https://software.ecmwf.int/wiki/display/GRIB/Home
    license: Apache License, Version 2.0
    summary: The ECMWF API for encoding and decoding WMO FM-92 GRIB edition 1 and edition 2 messages.
